### ISSUE TITLE
Number of participants

### ISSUE THREAD

**Issue by arilwan** [vlomonaco/US-TransportationMode#2]
Just willing to experiment with this data set, I downloaded it. However, the unzipped raw_data directory contains 16-users sub-directories: U1 - U16 as against 13 users stated here.

Is this deliberate or an update?

**Comment by vlomonaco** [comment]
Hi @arilwan! I think some of them were dropped due to little data. Everything should be explained  [here](http://cs.unibo.it/projects/us-tm2017/index.html)!

**Comment by arilwan** [comment]
Ah OK, many thanks.
